   language: python
   python:
      - "3.5"
   install:
      - pip install coveralls
      - pip install coverage
   script:
      - python3 test_rpn.py
      - coverage run test_rpn.py
   after_success:
      - coveralls
